- README.md
- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/values.yaml
Signed-off-by: relgisri <dennis@irsigler.cloud>
> bump versions

- .github/workflows/lint-test.yaml
- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/values.yaml
Signed-off-by: relgisri <dennis@irsigler.cloud>
> add k8s matrix

- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/values.yaml
Just bumping the default version of the uptime kuma docker image
> bumping uptime kuma version to 1.11.1

- README.md
- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/templates/NOTES.txt
- charts/uptime-kuma/templates/deployment.yaml
- charts/uptime-kuma/templates/pvc.yaml
- charts/uptime-kuma/values.yaml
> Adding option to change from STS to Deploy

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: relgisri <dennis@irsigler.cloud>
> added PullRequestTemplate

- README.md
- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/templates/pvc.yaml
In the PVC template a wrong value was referenced. This PR corrects the reference.
**Benefits**
storageClassName is usable
¯\\\_(ツ)\_/¯
- fixes #22 
¯\\\_(ツ)\_/¯
**Checklist**
> fix: storageClassName usage

- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/templates/ingress.yaml
In pull-request #9 extraLabels (for vhost) were added, which were
removed after the refactoring in #19 - re-introduce this config in this
pr to mitigate the regression
**Benefits**
Make ingress labels configuration work again
n/a
n/a
n/a
**Checklist**
> re-introduce ingress labels from #9

- charts/uptime-kuma/Chart.yaml
bump Chart version to fix release.
**Benefits**
n/a
n/a
n/a
n/a
**Checklist**
> bump Chart version to 2.1.2

- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/values.yaml
Uptime Kuma Docker Image
**Benefits**
New Uptime Kuma Version
¯\\\_(ツ)\_/¯
¯\\\_(ツ)\_/¯
¯\\\_(ツ)\_/¯
**Checklist**
> feat: bump uptime app version

- README.md
In addition to #30 this is the documentation and the start of the issue #33
> feat: docu podEnv

- .github/workflows/lint-test.yaml
- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/values.yaml
I changed the Kubernetes versions in the GitHub Actions Workflow to the currently supported Kubernetes versions.
**Benefits**
Getting the check for all supported k8s versions, and current patch releases.
Unsupported Kubernetes versions are not covered.
> Kubernetes versions workflow

- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/values.yaml
Bump the chart to a new uptime kuma app version.
**Checklist**
> New kuma version

- renovate.json
Signed-off-by: relgisri <dennis@irsigler.cloud>
**Benefits**
- fixes #55 
**Checklist**
> configure renovate.json

- .github/CODEOWNERS
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- README.md
- charts/uptime-kuma/README.md
Updates the README files and adds additional meta information.
> Add metadata

- .pre-commit-config.yaml
- renovate.json
- Add, hopefully fixed, renovate.json configuration to update Helm and GitHub Actions
- Add pre-commit config repository to validate renovatebot configuration
> Add renovatebot config

- README.md
> feat: change Helm repo URL

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
Both of the GitHub Actions workflows are currently not being triggered as the path to check for changes is incorrect. This PR fixes that.
**Benefits**
Makes the GitHub Actions workflows work again.
None.
None.
None.
**Checklist**
None.
> ci: fix paths for action triggers

- .github/configs/cr.yaml
- .github/workflows/release.yaml
- Added GPG signing steps to workflows
**Benefits**
- Security 🚀 
- Might break due to incompentence
- fixes #119 
**Checklist**
> (feat): add GPG signing steps

- .github/workflows/release.yaml
- charts/uptime-kuma/Chart.yaml
- charts/uptime-kuma/README.md
- bump version
**Benefits**
- trigger release and test GPG signing
- fixes #
**Checklist**
> (chore): bump version

- .github/workflows/release.yaml
**Benefits**
- fixes #
**Checklist**
> (fix): remove IFS

- charts/uptime-kuma/values.yaml
make it clear in values.yaml that user has to specify username as well
**Benefits**
user won't get confused by failing scraping
none
none
See my proposed changes to kuma wiki https://github.com/louislam/uptime-kuma-wiki/compare/master...elmariofredo:uptime-kuma-wiki:patch-1
**Checklist**
As this is purely documentation change I think it's not necessary to release new version, WDYT?
> (docs): slarify serviceMonitor basicAuth comment
